### PR TITLE
fix: getInterfaceNames so that it works in core-components

### PR DESCRIPTION
**Pull request by albertfolch-redeemeum**
as this repo is added in core-components as a submodule in another subfolder called _protocol-contracts_, our deploy script fails. This should fix it

### CODE REVIEW

**Review by zajck — COMMENTED** [review]
I'm wondering - can this be done more flexible?

What I mean is, if somebody just clones contract repo, `prefix` sort of makes sense to them, while  `prefixProtocolContracts` makes sense to them only if they are aware of core-component repo.
Or if we look from another perspective - if someone else starts using protocol contracts as submodule in their repo, they would need to come here and add their prefix. 

Maybe there is a more general solution than adding multiple prefixes? :thinking:

**Comment by levalleux-ludo** [comment]
> I'm wondering - can this be done more flexible?
> 
> What I mean is, if somebody just clones contract repo, `prefix` sort of makes sense to them, while `prefixProtocolContracts` makes sense to them only if they are aware of core-component repo. Or if we look from another perspective - if someone else starts using protocol contracts as submodule in their repo, they would need to come here and add their prefix.
> 
> Maybe there is a more general solution than adding multiple prefixes? 🤔

Agree with Klemen

**Review by levalleux-ludo — CHANGES_REQUESTED** [review]
see comments from Klemen and myself

**Comment by albertfolch-redeemeum** [comment]
changed @levalleux-ludo @zajck

**Review by zajck — APPROVED** [review]
LGTM :+1:

**Review by levalleux-ludo — APPROVED** [review]

**Pull request merged**
